### ISSUE TITLE
Fail to install Macos

### ISSUE THREAD

**Issue by theaveasso** [getbasedai/basedai#9]
Hi there, I went through the install via `pip install basedai` but it seems not to work

My setup
MacOS
Python 3.13.1

```
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      /private/var/folders/rf/1kwhlkn57qs15ncs0j549jww0000gn/T/pip-install-jzq_w6ha/basedai_011c5661815b4ca399c93afc4a7fe6b0/setup.py:19: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        from pkg_resources import parse_requirements
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
          exec(compile('''
          ~~~~^^^^^^^^^^^^
          # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ...<31 lines>...
          exec(compile(setup_py_code, filename, "exec"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ''' % ('/private/var/folders/rf/1kwhlkn57qs15ncs0j549jww0000gn/T/pip-install-jzq_w6ha/basedai_011c5661815b4ca399c93afc4a7fe6b0/setup.py',), "<pip-setuptools-caller>", "exec"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/rf/1kwhlkn57qs15ncs0j549jww0000gn/T/pip-install-jzq_w6ha/basedai_011c5661815b4ca399c93afc4a7fe6b0/setup.py", line 44, in <module>
          requirements = read_requirements("requirements/prod.txt")
        File "/private/var/folders/rf/1kwhlkn57qs15ncs0j549jww0000gn/T/pip-install-jzq_w6ha/basedai_011c5661815b4ca399c93afc4a7fe6b0/setup.py", line 33, in read_requirements
          with pathlib.Path(path).open() as requirements_txt:
               ~~~~~~~~~~~~~~~~~~~~~~~^^
        File "/Users/*/miniconda3/envs/based/lib/python3.13/pathlib/_local.py", line 537, in open
          return io.open(self, mode, buffering, encoding, errors, newline)
                 ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements/prod.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by theaveasso** [comment]
Issue seems my Python version is too high.
Got It works building from source. Cheers

**Comment by StarringLara** [comment]
> Issue seems my Python version is too high. Got It works building from source. Cheers

When you say your Python version was too high, are you saying just using 3.13.1 is too high? If so, this doesn't seem like a reason to close the issue to me as this is the latest officially stable Python version, so I imagine it should be fully supported and working with a normal pip install unless they explicitly say they don't support beyond a certain version, which I haven't seen anywhere.
